### ISSUE TITLE
Headline looks weird

### ISSUE THREAD

**Issue by Anja-Pe** [zpainter/iassist#72]
Hi Zac and Ryan,

I hope I'm doing this correctly by writing you here. I made my first changes to our Finding Data Guide and the group page. But one headline turned out weird: Copyright on this page has a black box arround it: https://iassistdata.org/community/antiracism-resources-guide/

And that is even though the preview looks okay and I did the same as for other headlines. Please let me know what I did wrong so I can fix it myself next time :-)

All the best,
Anja

**Comment by Anja-Pe** [comment]
Thank you! I added a blank line after each header now and I took the whole copyright section out, committed the changes, then put it back in. It still looks like this.

**Comment by zpainter** [comment]
Hello. This has been resolved on my end.

Best guess? "Copyright" alone as a header triggers some kind of style change. So I tagged in an extra word, and that seems to have gotten it.

**Comment by Anja-Pe** [comment]
Thank you, Zac! I had such a suspicion. So, it makes me happy that I wasn't too far off. Thank you for the easy fix! :-)
