### ISSUE TITLE
Link to document

### ISSUE THREAD

**Issue by Anja-Pe** [zpainter/iassist#74]
Good morning,

I'm updating the Conference Manual and Meryl added a section about the paper competition and sent me a spreadsheet for new organizers and reviewers to use. How can I link to this? Do we have a space where we store files to link to from the page?

Best,
Anja

**Comment by zpainter** [comment]
Most files can be stored in a directory of the same repo, or another folder in the structure. A good example are the non-md files in this location = https://github.com/zpainter/iassist/tree/master/content/community/antiracismresources-ig

That said, depending on what the spreadsheet actually is, you may prefer to have it come from some other source.

**Comment by Anja-Pe** [comment]
Thank you! I uploaded the file directly to the "conference" folder, but I still cannot link to it.

I have: [review spreadsheet](/content/conferences/2022-IASSIST-Papers-Competition-Review-Sheet.xlsx)

I also had it without "/content" earlier and that didn't work. It told me that there is no path called "conferences", that's why I added /content.

**Comment by zpainter** [comment]
This has been modified. I have moved the file path to an alternate location, and deleted the other one you uploaded. Let me know if this works for you.

**Comment by Anja-Pe** [comment]
Thank you! :-)
