### ISSUE TITLE
IG name change and links

### ISSUE THREAD

**Issue by Anja-Pe** [zpainter/iassist#76]
Hi Zac and Ryan,

I would like to implement the group's name change (from Anti-Racism Resources to Diversity, Equity, and Inclusion Data Resources). Is there anything I should be aware of?

Since I also wanted to change the website a bit, I was thinking to start a whole new page which can have a new link and it can go live whenever it's ready. Is that a way to go? 

Is it true that any new page/file that isn't linked from anywhere would be invisible and only become visible when I add the link in the relevant places? And can I look up from where the current page is linked, so that I can replace those links? 

Looking forward to your input :-)
Anja

**Comment by zpainter** [comment]
Assuming the name change was approved by AC in whatever capacity it needs to happen there, then probably nothing to actually do on that end.

It is a way to create a page and then go live whenever. If you do that, it might be best to create a new branch. Then you can test out all that you want on the new branch, before getting it ready to go live later. That is more of the standard practice, which also addresses some of your questions from the third paragraph. Let me know if you want some help on that part.

In theory you could get to any page that is published, even without the link visible. You would need to know the URL to do so.

**Comment by Anja-Pe** [comment]
Thank you, Zac! I will try that.

And the name change was approved by the AC in Philadelphia. We are all set there :-)

**Comment by Anja-Pe** [comment]
Thank you, Zac! I will try that.

And the name change was approved by the AC in Philadelphia. We are all set there :-)
